### ISSUE TITLE
The built in Internet plugin seems to not fully function on 10.12.4

### ISSUE THREAD

**Issue by WardsParadox** [ygini/Hello-IT#28]
The Internet state is staying orange (using the defaults in the wiki) even as I type this now. I have full internet connectivity on both wifi and ethernet.

**Comment by WardsParadox** [comment]
I do see this a lot on the Console for Hello IT.
13:24:22.785644 -0600	Hello IT	TIC TCP Conn Start [6:0x6000001986d0]
13:24:22.904363 -0600	Hello IT	TIC TCP Conn Event [6:0x6000001986d0]: 1 Err(0)
13:24:22.904429 -0600	Hello IT	TIC TCP Conn Connected [6:0x6000001986d0]: Err(0)

**Comment by ygini** [comment]
Yes, I've seen that too. The issue come from a small change in the testing URL hosted by Apple.

I've published a note for this on the wiki https://github.com/ygini/Hello-IT/wiki/public.test.http#shared-test-url

Tell me if it fix your issue

**Comment by WardsParadox** [comment]
Yup that fixes it! Thanks @ygini!
Note: Had to `killall cfprefsd` after loading in the new profiles.

**Comment by WardsParadox** [comment]
I am still getting orange flickers every now and again and I'm not sure where to start. 
I still get those errors in the log as well.

**Comment by ygini** [comment]
When you do a `defaults read com.github.ygini.Hello-IT` do get the right content?

**Comment by WardsParadox** [comment]
Does not exist. I am using a Profile to deploy the settings, not a preference file.

**Comment by ygini** [comment]
You're using profile but need to kill `cfprefsd`?! There is a problem here.

**Comment by WardsParadox** [comment]
I believe that was because I left the app open while I swapped the profile. There are no preference files on this machine or a clean test machine which is exhibiting the same behavior with a fresh install and the same profile.

**Comment by ygini** [comment]
So, if you do things in this order:
— update your profile content
— push/install it
— restart the app

What's the result?

**Comment by WardsParadox** [comment]
Same behavior as before with the apple captive portal. I did just find the issue. Looks like the MCX preferences aren't updating for some reason. 
`defaults read /Library/Managed\ Preferences/com.github.ygini.hello-it.plist` results in reading the old profile data.

**Comment by WardsParadox** [comment]
Ah HA! Found the issue. Looks like I managed to install the profile twice as two separate installs, I'm not sure how but I did! Let me do some more testing to see if this is now resolved.

**Comment by WardsParadox** [comment]
That was the issue. 😅 Thanks for the info and the fix.

**Comment by kiepenflicker** [comment]
The checksum 41ba060eb1c0898e0a4a0cca36a8ca91 works. Looks like Apple inserted a linefeed.

**Comment by ygini** [comment]
Be careful, the additional line break you see isn’t always here. That’s why I’ve updated the wiki to offer an alternative testing target.

Depending of my ISP, I got the old and new hash.
